apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: three-tier-app
  name: three-tier-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: three-tier-app
    spec:
      containers:
      - name: three-tier-container
        image: gcr.io/test-app/three-tier-app:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi