apiVersion: v1
kind: Service
metadata:
  name: three-tier-service
  namespace: default
  labels:
    app: three-tier-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: three-tier-app
