apiVersion: v1
data:
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  labels:
    deployedby: three-tier-yaml
  name: three-tier-db
  namespace: three-tier
type: Opaque
---
apiVersion: v1
data:
  password: cGFzc3dvcmQK
kind: Secret
metadata:
  annotations:
  labels:
    deployedby: three-tier-yaml
  name: three-tier-audit-db
  namespace: three-tier
type: Opaque
