apiVersion: v1
kind: Service
metadata:
  labels:
    app: three-tier-db
    three-tier.component: database
    deployedby: three-tier-yaml
  name: three-tier-db
  namespace: three-tier
spec:
  ports:
    - port: 5432
  selector:
    app: three-tier-db
  type: ClusterIP 